@echo off
rem This file has been generated by the Pastagames Linguini Tool ShaderCommandBuilder (GameEngineFwk/modules/Shaders/CommandBuilder)
rem From file shaderConfigFile.lua

cd 
set SHADER_CONVERTER=%NINTENDO_SDK_ROOT%\Tools\Graphics\GraphicsTools\ShaderConverter
set INC_DIRS=--include-directory ..
set ARGS1_FS=--glsl-version 330 --glslc-option-flags="--errorOnScratchMemUsage=1" --separable --reflection-full --preprocessor-definition PASTA_GLSL --preprocessor-definition PASTA_OGLES --preprocessor-definition PASTA_FRAGMENT_SHADER --preprocessor-definition PASTA_NX --debug-info-level="High"
set ARGS1_VS=--glsl-version 140 --glslc-option-flags="--errorOnScratchMemUsage=1" --separable --reflection-full --preprocessor-definition PASTA_GLSL --preprocessor-definition PASTA_OGLES --preprocessor-definition PASTA_VERTEX_SHADER --preprocessor-definition PASTA_NX --debug-info-level="High"
set ARGS1_CS=--glsl-version 430 --glslc-option-flags="--errorOnScratchMemUsage=1" --separable --reflection-full --preprocessor-definition PASTA_GLSL --preprocessor-definition PASTA_OGLES --preprocessor-definition PASTA_COMPUTE_SHADER --preprocessor-definition PASTA_NX --debug-info-level="High"
set ARGS2=-s glsl --code-type="Binary" -a nvn --shader-cache-directory cache --debug-info-directory debug

call %SHADER_CONVERTER% %ARGS1_VS% --vertex-shader "glsl/Room_vs.glsl" %ARGS2% %INC_DIRS% -o "switch/Room_vs.bnsh"
if errorlevel 1 (
  echo Failure Reason is %errorlevel%
  color 0c
  pause
  exit /b %errorlevel%
)
call %SHADER_CONVERTER% %ARGS1_FS% --pixel-shader "glsl/Room_fs.glsl" %ARGS2% %INC_DIRS% -o "switch/Room_fs.bnsh"
if errorlevel 1 (
  echo Failure Reason is %errorlevel%
  color 0c
  pause
  exit /b %errorlevel%
)
call %SHADER_CONVERTER% %ARGS1_VS% --vertex-shader "glsl/Room_vs.glsl" %ARGS2% %INC_DIRS% -o "switch/Room_vs_59afd28f.bnsh" --preprocessor-definition EARLY_DEPTH
if errorlevel 1 (
  echo Failure Reason is %errorlevel%
  color 0c
  pause
  exit /b %errorlevel%
)
call %SHADER_CONVERTER% %ARGS1_FS% --pixel-shader "glsl/Room_fs.glsl" %ARGS2% %INC_DIRS% -o "switch/Room_fs_ab897fdf.bnsh" --preprocessor-definition EARLY_DEPTH
if errorlevel 1 (
  echo Failure Reason is %errorlevel%
  color 0c
  pause
  exit /b %errorlevel%
)
