@echo off
rem This file has been generated by the Pastagames Linguini Tool ShaderCommandBuilder (GameEngineFwk/modules/Shaders/CommandBuilder)
rem From file computeConfigFile.lua

cd 
set SHADER_CONVERTER=%NINTENDO_SDK_ROOT%\Tools\Graphics\GraphicsTools\ShaderConverter
set INC_DIRS=--include-directory ..
set ARGS1_FS=--glsl-version 430 --glslc-option-flags="--errorOnScratchMemUsage=1" --separable --reflection-full --preprocessor-definition PASTA_GLSL --preprocessor-definition PASTA_OGLES --preprocessor-definition PASTA_FRAGMENT_SHADER --preprocessor-definition PASTA_NX --debug-info-level="High"
set ARGS1_VS=--glsl-version 430 --glslc-option-flags="--errorOnScratchMemUsage=1" --separable --reflection-full --preprocessor-definition PASTA_GLSL --preprocessor-definition PASTA_OGLES --preprocessor-definition PASTA_VERTEX_SHADER --preprocessor-definition PASTA_NX --debug-info-level="High"
set ARGS1_CS=--glsl-version 430 --glslc-option-flags="--errorOnScratchMemUsage=1" --separable --reflection-full --preprocessor-definition PASTA_GLSL --preprocessor-definition PASTA_OGLES --preprocessor-definition PASTA_COMPUTE_SHADER --preprocessor-definition PASTA_NX --debug-info-level="High"
set ARGS2=-s glsl --code-type="Binary" -a nvn --shader-cache-directory cache --debug-info-directory debug

call %SHADER_CONVERTER% %ARGS1_CS% --compute-shader "glsl/UpdateParticle_cs.glsl" %ARGS2% %INC_DIRS% -o "switch/UpdateParticle_cs_f2aa663b.bnsh" --preprocessor-definition PASTA_LOCAL_SIZE_X=1024 --preprocessor-definition MAX_PARTICLES=1024
if errorlevel 1 (
  echo Failure Reason is %errorlevel%
  color 0c
  pause
  exit /b %errorlevel%
)
call %SHADER_CONVERTER% %ARGS1_CS% --compute-shader "glsl/UpdateParticle_cs.glsl" %ARGS2% %INC_DIRS% -o "switch/UpdateParticle_cs_2e235f25.bnsh" --preprocessor-definition PASTA_LOCAL_SIZE_X=1024 --preprocessor-definition MAX_PARTICLES=1024 --preprocessor-definition HAS_TEXTURE
if errorlevel 1 (
  echo Failure Reason is %errorlevel%
  color 0c
  pause
  exit /b %errorlevel%
)
call %SHADER_CONVERTER% %ARGS1_CS% --compute-shader "glsl/UpdateParticle_cs.glsl" %ARGS2% %INC_DIRS% -o "switch/UpdateParticle_cs_00c4a717.bnsh" --preprocessor-definition PASTA_LOCAL_SIZE_X=1024 --preprocessor-definition MAX_PARTICLES=1024 --preprocessor-definition HAS_COLOR_DATA
if errorlevel 1 (
  echo Failure Reason is %errorlevel%
  color 0c
  pause
  exit /b %errorlevel%
)
call %SHADER_CONVERTER% %ARGS1_CS% --compute-shader "glsl/UpdateParticle_cs.glsl" %ARGS2% %INC_DIRS% -o "switch/UpdateParticle_cs_9fbc7011.bnsh" --preprocessor-definition PASTA_LOCAL_SIZE_X=1024 --preprocessor-definition MAX_PARTICLES=1024 --preprocessor-definition HAS_COLOR_DATA --preprocessor-definition HAS_TEXTURE
if errorlevel 1 (
  echo Failure Reason is %errorlevel%
  color 0c
  pause
  exit /b %errorlevel%
)
call %SHADER_CONVERTER% %ARGS1_CS% --compute-shader "glsl/UpdateParticle_cs.glsl" %ARGS2% %INC_DIRS% -o "switch/UpdateParticle_cs_3c2d3bf6.bnsh" --preprocessor-definition PASTA_LOCAL_SIZE_X=1024 --preprocessor-definition MAX_PARTICLES=2048
if errorlevel 1 (
  echo Failure Reason is %errorlevel%
  color 0c
  pause
  exit /b %errorlevel%
)
call %SHADER_CONVERTER% %ARGS1_CS% --compute-shader "glsl/UpdateParticle_cs.glsl" %ARGS2% %INC_DIRS% -o "switch/UpdateParticle_cs_6bb495dc.bnsh" --preprocessor-definition PASTA_LOCAL_SIZE_X=1024 --preprocessor-definition MAX_PARTICLES=2048 --preprocessor-definition HAS_TEXTURE
if errorlevel 1 (
  echo Failure Reason is %errorlevel%
  color 0c
  pause
  exit /b %errorlevel%
)
call %SHADER_CONVERTER% %ARGS1_CS% --compute-shader "glsl/UpdateParticle_cs.glsl" %ARGS2% %INC_DIRS% -o "switch/UpdateParticle_cs_c8cd01d6.bnsh" --preprocessor-definition PASTA_LOCAL_SIZE_X=1024 --preprocessor-definition MAX_PARTICLES=2048 --preprocessor-definition HAS_COLOR_DATA
if errorlevel 1 (
  echo Failure Reason is %errorlevel%
  color 0c
  pause
  exit /b %errorlevel%
)
call %SHADER_CONVERTER% %ARGS1_CS% --compute-shader "glsl/UpdateParticle_cs.glsl" %ARGS2% %INC_DIRS% -o "switch/UpdateParticle_cs_9b72ff7c.bnsh" --preprocessor-definition PASTA_LOCAL_SIZE_X=1024 --preprocessor-definition MAX_PARTICLES=2048 --preprocessor-definition HAS_COLOR_DATA --preprocessor-definition HAS_TEXTURE
if errorlevel 1 (
  echo Failure Reason is %errorlevel%
  color 0c
  pause
  exit /b %errorlevel%
)
call %SHADER_CONVERTER% %ARGS1_VS% --vertex-shader "glsl/Particle_vs.glsl" %ARGS2% %INC_DIRS% -o "switch/Particle_vs_706f4dd0.bnsh" --preprocessor-definition MAX_PARTICLES=1024
if errorlevel 1 (
  echo Failure Reason is %errorlevel%
  color 0c
  pause
  exit /b %errorlevel%
)
call %SHADER_CONVERTER% %ARGS1_VS% --vertex-shader "glsl/Particle_vs.glsl" %ARGS2% %INC_DIRS% -o "switch/Particle_vs_8a0a684e.bnsh" --preprocessor-definition MAX_PARTICLES=1024 --preprocessor-definition HAS_TEXTURE
if errorlevel 1 (
  echo Failure Reason is %errorlevel%
  color 0c
  pause
  exit /b %errorlevel%
)
call %SHADER_CONVERTER% %ARGS1_VS% --vertex-shader "glsl/Particle_vs.glsl" %ARGS2% %INC_DIRS% -o "switch/Particle_vs_aad98edc.bnsh" --preprocessor-definition MAX_PARTICLES=1024 --preprocessor-definition HAS_COLOR_DATA
if errorlevel 1 (
  echo Failure Reason is %errorlevel%
  color 0c
  pause
  exit /b %errorlevel%
)
call %SHADER_CONVERTER% %ARGS1_VS% --vertex-shader "glsl/Particle_vs.glsl" %ARGS2% %INC_DIRS% -o "switch/Particle_vs_511949aa.bnsh" --preprocessor-definition MAX_PARTICLES=1024 --preprocessor-definition HAS_COLOR_DATA --preprocessor-definition HAS_TEXTURE
if errorlevel 1 (
  echo Failure Reason is %errorlevel%
  color 0c
  pause
  exit /b %errorlevel%
)
call %SHADER_CONVERTER% %ARGS1_VS% --vertex-shader "glsl/Particle_vs.glsl" %ARGS2% %INC_DIRS% -o "switch/Particle_vs_79b77dd1.bnsh" --preprocessor-definition MAX_PARTICLES=2048
if errorlevel 1 (
  echo Failure Reason is %errorlevel%
  color 0c
  pause
  exit /b %errorlevel%
)
call %SHADER_CONVERTER% %ARGS1_VS% --vertex-shader "glsl/Particle_vs.glsl" %ARGS2% %INC_DIRS% -o "switch/Particle_vs_44f66323.bnsh" --preprocessor-definition MAX_PARTICLES=2048 --preprocessor-definition HAS_TEXTURE
if errorlevel 1 (
  echo Failure Reason is %errorlevel%
  color 0c
  pause
  exit /b %errorlevel%
)
call %SHADER_CONVERTER% %ARGS1_VS% --vertex-shader "glsl/Particle_vs.glsl" %ARGS2% %INC_DIRS% -o "switch/Particle_vs_08637a51.bnsh" --preprocessor-definition MAX_PARTICLES=2048 --preprocessor-definition HAS_COLOR_DATA
if errorlevel 1 (
  echo Failure Reason is %errorlevel%
  color 0c
  pause
  exit /b %errorlevel%
)
call %SHADER_CONVERTER% %ARGS1_VS% --vertex-shader "glsl/Particle_vs.glsl" %ARGS2% %INC_DIRS% -o "switch/Particle_vs_a640b4a3.bnsh" --preprocessor-definition MAX_PARTICLES=2048 --preprocessor-definition HAS_COLOR_DATA --preprocessor-definition HAS_TEXTURE
if errorlevel 1 (
  echo Failure Reason is %errorlevel%
  color 0c
  pause
  exit /b %errorlevel%
)
call %SHADER_CONVERTER% %ARGS1_FS% --pixel-shader "glsl/Particle_fs.glsl" %ARGS2% %INC_DIRS% -o "switch/Particle_fs.bnsh"
if errorlevel 1 (
  echo Failure Reason is %errorlevel%
  color 0c
  pause
  exit /b %errorlevel%
)
